# https://github.com/tamasfe/taplo/blob/master/site/site/cli/usage/configuration.md#configuration-file
include = ["**/*.toml"]

[formatting]
# Align entries vertically. Entries that have table headers, comments, or blank lines between them are not aligned.
# default: false
align_entries = false
# Align consecutive comments after entries and items vertically. This applies to comments that are after entries or array items.
# default: true
align_comments = true
# Put trailing commas for multiline arrays.
# default: true
array_trailing_comma = true
# Automatically expand arrays to multiple lines when they exceed column_width characters.
# default: true
array_auto_expand = false
# Automatically collapse arrays if they fit in one line.
# default: true
array_auto_collapse = true
# Omit whitespace padding inside single-line arrays.
# default: true
compact_arrays = true
# Omit whitespace padding inside inline tables.
# default: false
compact_inline_tables = false
# Expand values (e.g. arrays) inside inline tables.
# default: true
inline_table_expand = true
# Omit whitespace around =.
# default: flase
compact_entries = false
# Target maximum column width after which arrays are expanded into new lines.
# default: 80
column_width = 80
# Indent subtables if they come in order.
# default: flase
indent_tables = false
# Indent entries under tables.
# default: flase
indent_entries = false
# Indentation to use, should be tabs or spaces but technically could be anything.
# default: 2 spaces (" ")
indent_string = "  "
# Add trailing newline to the source.
# default: true
trailing_newline = true
# Alphabetically reorder keys that are not separated by blank lines.
# default: false
reorder_keys = false
# Alphabetically reorder array values that are not separated by blank lines.
# default: false
reorder_arrays = false
# The maximum amount of consecutive blank lines allowed.
# default: 2
allowed_blank_lines = 1
# Use CRLF line endings.
# default: false
crlf = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["*-dependencies", "*.*.dependencies", "*.dependencies", "dependencies", "features"]

[rule.formatting]
array_auto_expand = false
reorder_keys = true
reorder_arrays = true
