# [".config/zsh/ohmyzsh"]
# type = "git-repo"
# url = "https://github.com/ohmyzsh/ohmyzsh.git"
# exact = true
# stripComponents = 1
# refreshPeriod = "168h"

[".config/nvim"]
type = "git-repo"
url = "git@github.com:duminghui/nvim-cfg.git"
# disables refreshes
refreshPeriod = 0
