# 注释的第一列是默认值
# array_width = 60                       # 60
# attr_fn_like_width = 70                # 70
# binop_separator = "Front"              # Front, Back
# blank_lines_lower_bound = 0            # 0
# blank_lines_upper_bound = 1            # 1
# brace_style = "SameLineWhere" # SameLineWhere, AlwaysNextLine, PreferSameLine
# chain_width = 30 # 60
# color = "Auto"                         # Auto, Always Never
# combine_control_expr = true            # true, false
# comment_width = 0 # 80
# condense_wildcard_suffixes = false     # false, true
# control_brace_style = "AlwaysSameLine" # AlwaysNetLine, AlwaysSameLine, ClosingNextLine
# disable_all_formatting = false         # false, true
# edition = "2021" # 2015, 2018, 2021
empty_item_single_line = false    # true, false
enum_discrim_align_threshold = 60 # 0
# error_on_line_overflow = false         # false, true
# error_on_unformatted = false           # false, true
# fn_args_layout = "Tall"                # Tall, Compressed, Vertical
# fn_call_width = 30 # 60
# fn_single_line = true # false, true
# force_explicit_abi = true              # true, false
# force_multiline_blocks = false         # false, true
format_code_in_doc_comments = true # false, true
# format_generated_files = false         # false, true
format_macro_matchers = true # false, true
# format_macro_bodies = true   # true, false
# format_strings = false # false, true
# hard_tabs = false                      # false, true
# hex_literal_case = "Preserve"          # Preserve, Upper, Lower
# hide_parse_errors = false              # false, true
# ignore = []                            # See Document
# imports_indent = "Block"               # Block, Visual
# imports_layout = "Mixed"               # Mixed, Horizontal, HorizontalVertical, Vertical
# indent_style = "Visual" # Block, Visual
# inline_attribute_widht = 0             # 0
# license_template_path = ""             # ""
# match_arm_blocks = true                # true, false
# match_arm_leading_pipes = "Never"      # Never, Always, Preserve
match_block_trailing_comma = true # false, true
max_width = 120                   # 100
# merge_derives = true                   # true, false
imports_granularity = "Module" # Preserve, Crate, Module, Item, One
# newline_style = "Auto"                 # Auto, Native, Unix, Windows
# normalize_comments = false             # false, true
normalize_doc_attributes = true # false, true
# overflow_delimited_expr = false        # false, true
# remove_nested_parens = true            # true, false
reorder_impl_items = true # false, true
# reorder_imports = true                 # true, false
group_imports = "StdExternalCrate" # Preserve, StdExternalCrate
# reorder_modules = true                 # true, false
# report_fixme = "Never"                 # Never, Always,  Unnumbered
# report_todo = "Never"                  # Never, Always, Unnumbered
# required_version = "CARGO_PKG_VERSION" # any published version (e.g. "0.3.8"), any published version (e.g. "0.3.8")
# skip_children = false                  # false, true
# single_line_if_else_max_width = 50     # 50
# space_after_colon = true               # true, false
# space_before_colon = false             # false, true
# space_around_ranges = false            # false, true
struct_field_align_threshold = 60 # 0
# struct_lit_single_line = false # true, false
# struct_lit_width = 18                  # 18
# struct_variant_width = 35              # 35
# tab_spaces = 4                         # 4
# trailing_comma = "Vertical"            # Vertical, Always, Never
# trailing_semicolon = true              # true,false
# type_punctuation_density = "Wide"      # Wide, Compressed
# unstable_feature = false               # false, true
# use_field_init_shorthand = false       # false, true
# use_small_heuristics = "Default" # Default, Off, Max
use_try_shorthand = true # false, true
# version = "Two"          # One, Two
# where_single_line = true # false, true
# wrap_comments = true # false, true
