# use name has bug

# 191 items
name:
  .android: 󰀲
  .cache: 󰃨
  .condarc: 󰌠
  .docker: 󰡨
  .gradle: 
  .localized: 󰀵
  .m2: 
  .yarnrc.yml: 
  .zshenv: 
  android: 󰀲
  "applications (parallels)": 󰜨
  fish: 󰈺
  library: 󰁰
  movies: 󰎁
  parallels: 󰜨
  tmux: 󰕮
  work: 󰃖
  a.out: 
  api: 󰒍
  .atom: 󰝨
  authorized_keys: 󰿃
  backups: 󰁯
  .bash_logout: 󰒓
  .bash_profile: 󰒓
  .bashrc: 
  bin: 󱁿
  .bpython_history: 󰌠
  bspwmrc: 󰒓
  cargo.lock: 󱘗
  cargo.toml: 󱘗
  .cargo: 󱘗
  changelog: 󰍔
  .clang-format: 󰒓
  composer.json: 󰌟
  conf.d: 󱁿
  config.ac: 󰒓
  config.el: 
  config.mk: 󰒓
  .config: 󱁿
  config: 󰒓
  contributing: 󰿃
  copyright: 󰿃
  cron.daily: 󱁿
  cron.d: 󱁿
  cron.hourly: 󱁿
  cron.monthly: 󱁿
  crontab: 󰒓
  cron.weekly: 󱁿
  crypttab: 󰒓
  css: 󰌜
  custom.el: 
  .dbus: 󰒓
  desktop: 󰇄
  docker-compose.yml: 󰡨
  dockerfile: 󰡨
  doc: 󰂺
  documents: 󰂺
  .doom.d: 
  downloads: 󱧨
  .ds_store: 󰀵
  .editorconfig: 󰒓
  .emacs.d: 
  .env: 󰙪
  .eslintrc.json: 󰙪
  .eslintrc.js: 󰙪
  .eslintrc.yml: 󰙪
  etc: 󱁿
  favicon.ico: 󰓎
  favicons: 󰓎
  fstab: 󰆼
  .gitattributes: 󰊢
  .gitconfig: 󰊢
  .git-credentials: 󰿃
  .github: 󰊤
  gitignore_global: 󰊢
  .gitignore: 󰊢
  .gitlab-ci.yml: 󰮠
  .gitmodules: 󰊢
  .git: 󰊢
  .gnupg: 󰌾
  gradle: 
  group: 󰒓
  gruntfile.coffee: 
  gruntfile.js: 
  gruntfile.ls: 
  gshadow: 󰒓
  gulpfile.coffee: 
  gulpfile.js: 
  gulpfile.ls: 
  hidden: 󰌾
  home: 󰋜
  hostname: 󰒓
  hosts: 󰀂
  .htaccess: 󰒓
  htoprc: 󰒓
  .htpasswd: 󰒓
  .idlerc: 󰌠
  img: 󰈟
  include: 󱁿
  init.el: 
  .inputrc: 󰒓
  inputrc: 󰒓
  js: 󰌞
  .jupyter: 󰌠
  kbuild: 󰒓
  kconfig: 󰒓
  known_hosts: 󰿃
  .kshrc: 
  lib64: 󰗀
  lib: 󰗀
  license.md: 󰿃
  licenses: 󰿃
  license.txt: 󰿃
  license: 󰿃
  localized: 󰀵
  lsb-release: 󰒓
  .lynxrc: 󰒓
  .mailcap: 󰗰
  mail: 󰗰
  maintainers: 󰿃
  makefile.ac: 󰒓
  makefile: 󰒓
  manifest: 󰐣
  metadata: 󱁿
  metadata.xml: 󰙪
  mime.types: 󰙅
  module.symvers: 󰱾
  .mozilla: 
  music: 󰋋
  muttrc: 󰒓
  .mutt: 󰒓
  netlify.toml: 󰒋
  node_modules: 󰛷
  .node_repl_history: 󰎙
  npmignore: 󰛷
  .npm: 󰛷
  nvim: 
  os-release: 󰒓
  package.json: 󰎙
  package-lock.json: 󰎙
  packages.el: 
  passwd: 󰌾
  pictures: 󰏜
  pkgbuild: 󰣇
  .pki: 󰌾
  portage: 󱁿
  profile: 󰒓
  .profile: 
  public: 󰀄
  __pycache__: 󰌠
  .python_history: 󰌠
  rc.lua: 󰒓
  readme: 󰍔
  .release.toml: 󱘗
  requirements.txt: 󰌠
  robots.txt: 󱚝
  root: 󰌾
  rubydoc: 󰫏
  runtime.txt: 󰌠
  .rustup: 󱘗
  .rvm: 󰴭
  sass: 󰟬
  sbin: 󱁿
  scripts: 
  scss: 󰟬
  shadow: 󰒓
  share: 󱞬
  .shellcheckrc: 󰒓
  shells: 󰒓
  .sqlite_history: 
  src: 󰗀
  .ssh: 󰌾
  styles: 󰌜
  sudoers: 󰌾
  sxhkdrc: 󰒓
  tigrc: 󰒓
  tox.ini: 󰌠
  .trash: 󰩹
  ts: 󰛦
  unlicense: 󰿃
  url: 󰇧
  user-dirs.dirs: 󱁿
  vagrantfile: 󰒓
  venv: 󰌠
  videos: 󰕧
  .viminfo: 
  .vimrc: 
  vimrc: 
  .vim: 
  vim: 
  .vscode: 󰨞
  webpack.config.js: 󰜫
  .wgetrc: 󰒓
  wgetrc: 󰒓
  .xauthority: 󰒓
  .Xauthority: 󰒓
  xbps.d: 󱁿
  .xinitrc: 󰒓
  .xmodmap: 󰒓
  .Xmodmap: 󰒓
  xmonad.hs: 󰒓
  xorg.conf.d: 󱁿
  .xprofile: 󰒓
  .Xprofile: 󰒓
  .xresources: 󰒓
  zathurarc: 󰒓
  .zsh_history: 󰒓
  .zshrc: 

# 284 items
extension:
  1: 󰂺
  2: 󰂺
  3: 󰂺
  4: 󰂺
  5: 󰂺
  6: 󰂺
  7: 󰂺
  7z: 󰗄
  8: 󰂺
  ai: 
  ape: 󰮥
  apk: 󰀲
  asc: 󰌾
  asm: 󰱾
  asp: 󰗀
  a: 
  avi: 󰈰
  avro: 󰅩
  awk: 
  bak: 󰁯
  bash_history: 
  bash_profile: 
  bashrc: 
  bash: 
  bat: 󰖳
  bin: 
  bio: 󰐑
  bmp: 󰈟
  bz2: 󰗄
  cc: 󰙲
  cfg: 󰒓
  cjs: 󰌞
  class: 󰬷
  cljs: 
  clj: 
  cls: 
  cl: 󰅲
  coffee: 󰅶
  conf: 󰒓
  cpp: 󰙲
  cp: 󰙲
  cshtml: 󰁥
  csh: 
  csproj: 󰌛
  css: 󰌜
  cs: 󰌛
  csv: 󰈛
  csx: 󰌛
  cts: 󰛦
  c++: 󰙲
  c: 󰙱
  cue: 󰮥
  cxx: 󰙲
  dart: 
  dat: 󰆼
  db: 󰆼
  deb: 󰀼
  desktop: 󰇄
  diff: 
  dll: 󰖳
  dockerfile: 󰡨
  doc: 󰈬
  docx: 󰈬
  ds_store: 󰀵
  dump: 󰆼
  ebook: 󰗚
  ebuild: 󰣨
  eclass: 󰣨
  editorconfig: 󰒓
  ejs: 󰅴
  elc: 󰅲
  elf: 
  elm: 
  el: 󰅲
  env: 󰙪
  eot: 󰛖
  epub: 󰗚
  erb: 󰫏
  erl: 
  exe: 󰖳
  exs: 
  ex: 
  fish: 󰈺
  flac: 󰮥
  flv: 󰈰
  font: 󰛖
  fpl: 󰐑
  fsi: 
  fs: 
  fsx: 
  gdoc: 󰈬
  gemfile: 󰴭
  gemspec: 󰴭
  gform: 
  gif: 󰈟
  git: 󰊢
  go: 󰟓
  gradle: 
  gsheet: 󰈛
  gslides: 󰈧
  guardfile: 󰴭
  gz: 󰗄
  hbs: 󱗞
  heic: 󰈟
  heif: 󰈟
  heix: 󰈟
  hh: 󰬏
  hpp: 󰬏
  hs: 󰲒
  html: 󰌝
  htm: 󰌝
  h: 󰬏
  hxx: 󰬏
  ico: 󰈟
  image: 󰈟
  img: 󰆼
  iml: 
  info: 
  ini: 󰒓
  ipynb: 󰌠
  iso: 󰆼
  j2: 
  jar: 󰬷
  java: 󰬷
  jinja: 
  jl: 
  jpeg: 󰈥
  jpg: 󰈥
  jsonc: 󰘦
  json: 󰅩
  js: 󰌞
  jsx: 󰜈
  key: 󰿃
  ksh: 
  kt: 󱈙
  kts: 󱈙
  ldb: 󰆼
  ld: 
  less: 
  lhs: 󰲒
  license: 󰿃
  lisp: 󰅲
  list: 󰕲
  localized: 󰀵
  lock: 󰌾
  log: 󰘋
  lss: 󰌜
  lua: 󰢱
  lz: 󰗄
  m3u8: 󰐑
  m3u: 󰐑
  m4a: 󰮥
  m4v: 󰈰
  magnet: 󰍇
  man: 󰂺
  markdown: 󰍔
  md: 󰍔
  mjs: 󰌞
  mkd: 󰍔
  mk: 󰣖
  mkv: 󰈰
  mobi: 󰗚
  mov: 󰈰
  mp3: 󰮥
  mp4: 󰈰
  msi: 󰖳
  mts: 󰛦
  mustache: 󱗞
  nix: 󱄅
  npmignore: 󰛷
  ogg: 󰮥
  ogv: 󰈰
  old: 󰁯
  opus: 󰮥
  orig: 󰁯
  otf: 󰛖
  o: 
  pdf: 󰈦
  pem: 󰌆
  phar: 󰌟
  php: 󰌟
  pkg: 󰀼
  plist: 󰀵
  pls: 󰐑
  pl: 
  pm: 
  png: 󰈟
  ppt: 󰈧
  pptx: 󰈧
  procfile: 󰴭
  properties: 󰅩
  ps1: 
  psd: 
  pub: 󰿃
  pxm: 󰈟
  pyc: 󰌠
  py: 󰌠
  rakefile: 󰴭
  rar: 󰗄
  razor: 󰁥
  rb: 󰴭
  rdata: 󰟔
  rdb: 
  rdoc: 󰍔
  rds: 󰟔
  readme: 󰍔
  rlib: 󱘗
  rl: 󰌌
  rmd: 󰍔
  rpm: 󰀼
  rproj: 󰗆
  rspec_parallel: 󰴭
  rspec_status: 󰴭
  rspec: 󰴭
  rss: 󰑬
  rs: 󱘗
  rtf: 󰈙
  rubydoc: 󰫏
  r: 󰟔
  ru: 󰴭
  sass: 󰟬
  scala: 
  scpt: 󰀵
  scss: 󰟬
  shell: 
  sh: 
  sig: 󰿃
  slim: 󰫏
  sln: 󰨞
  so: 
  sqlite3: 
  sql: 󰆼
  srt: 󰂺
  styl: 
  stylus: 
  sublime-package: 󰬚
  sublime-session: 󰬚
  sub: 󰂺
  s: 󰱾
  svg: 󰈟
  swift: 󰛥
  swp: 
  sym: 
  tar: 󰗄
  tex: 
  tgz: 󰗄
  tiff: 󰈟
  toml: 󰅩
  torrent: 󰒍
  trash: 󰩹
  ts: 󰛦
  tsx: 󰜈
  ttc: 󰛖
  ttf: 󰛖
  t: 
  twig: 
  txt: 󰈙
  video: 󰈰
  vim: 
  vlc: 󰐑
  vue: 󰹭
  wav: 󰮥
  webm: 󰈰
  webp: 󰈟
  windows: 󰖳
  wma: 󰮥
  wmv: 󰈰
  woff2: 󰛖
  woff: 󰛖
  wpl: 󰐑
  xbps: 󰀼
  xcf: 󰈟
  xls: 󰈛
  xlsx: 󰈛
  xml: 󰗀
  xul: 󰈹
  xz: 󰗄
  yaml: 󰅩
  yml: 󰅩
  zip: 󰗄
  zshrc: 
  zsh-theme: 
  zsh: 
  zst: 󰗄

filetype:
  dir: 󰝰
  file: 󰈔
  pipe: 󰈲
  socket: 󰾳
  executable: 
  symlink-dir: 󱧮
  symlink-file: 󰪹
  device-char: 
  device-block: 󰜫
  special: 󰜗
