[helpers]

[default]
depends = []

[default.files]
# "bash/bash_profile" = "~/.bash_profile"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"
condarc = "~/.condarc"
"git/config" = "~/.config/git/config"
"git/config.local" = "~/.config/git/config.local"
"git/ignore" = "~/.config/git/ignore"
"ideavimrc" = "~/.ideavimrc"
# "kitty.config" = "~/.kitty"
"nodejs/npmrc" = "~/.npmrc"
"nodejs/yarnrc" = "~/.yarnrc"
nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }
"pip.conf" = "~/.config/pip/pip.conf"
"rust/cargo-config.toml" = "~/.cargo/config.toml"
"rust/rustfmt.toml" = "~/Library/Application Support/rustfmt/rustfmt.toml"
ssh-config = "~/.ssh/config"
"starship.toml" = "~/.config/starship.toml"
tmux = { target = "~/.config/tmux", type = "symbolic", recurse = false }

[default.variables]

[fish.files]
"fish/fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }
"fish/omf" = { target = "~/.config/omf", type = "symbolic", recurse = false }

[zsh.files]
"zsh/zshenv" = "~/.zshenv"
"zsh" = { target = "~/.config/zsh", type = "symbolic", recurse = false }
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/zprofile" = "~/.config/zsh/.zprofile"
