[helpers]

[default]
depends = []

[default.files]
# "bash/bash_profile" = "~/.bash_profile"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"
"cargo-config.toml" = "~/.cargo/config.toml"
condarc = "~/.condarc"
"git/gitconfig" = "~/.gitconfig"
"git/gitconfig.local" = "~/.gitconfig.local"
"git/gitignore" = "~/.gitignore"
"ideavimrc" = "~/.ideavimrc"
# "kitty.config" = "~/.kitty"
"nodejs/npmrc" = "~/.npmrc"
"nodejs/yarnrc" = "~/.yarnrc"
nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }
"pip.conf" = "~/.config/pip/pip.conf"
"rust/rustfmt.toml" = "~/Library/Application Support/rustfmt/rustfmt.toml"
ssh-config = "~/.ssh/config"
"tmux/tmux.conf" = "~/.tmux.conf"
"tmux/tmux.conf.colors" = "~/.tmux.conf.colors"

[default.variables]

[zsh.files]
"zsh/zprofile" = "~/.zprofile"
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"
"zsh/custom-zsh" = { target = "~/.custom-zsh", type = "symbolic", recurse = false }
